[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  AUTH0_DOMAIN = "your-auth0-domain.auth0.com"
  AUTH0_CLIENT_ID = "your-auth0-client-id"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 