backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "software"
    label: "Software Projects"
    folder: "content/software"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", required: false, hint: "Lower numbers appear first. Leave empty to sort by date." }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tech Stack", name: "tech", widget: "list" }
      - { label: "GitHub Link", name: "github", widget: "string", required: false }
      - { label: "GitHub Link Text", name: "github_text", widget: "string", required: false, hint: "Text to display on the GitHub link button" }
      - { label: "Live Demo", name: "demo", widget: "string", required: false }
      - { label: "Demo Link Text", name: "demo_text", widget: "string", required: false, hint: "Text to display on the demo link button" }
      - { label: "Gallery", name: "gallery", widget: "list", required: false, hint: "Add multiple images to display in a gallery", fields: [{ label: "Image", name: "image", widget: "image" }] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "art"
    label: "Creative"
    folder: "content/art"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", required: false, hint: "Lower numbers appear first. Leave empty to sort by date." }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Playwriting", "Visual Art", "Performance", "Other"] }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "External Link", name: "link", widget: "string", required: false }
      - { label: "Link Text", name: "link_text", widget: "string", required: false, hint: "Text to display on the external link button" }
      - { label: "Gallery", name: "gallery", widget: "list", required: false, hint: "Add multiple images to display in a gallery", fields: [{ label: "Image", name: "image", widget: "image" }] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Profile Image", name: "image", widget: "image" }
          - { label: "Developer Bio", name: "developer_bio", widget: "markdown" }
          - { label: "Artist Bio", name: "artist_bio", widget: "markdown" } 